version: '3'
services:
  core:
    container_name: easycore
    image: easycore
    build: .
    restart: always
    ports:
      - "5000:80"
    volumes:
      - .:/app

  demo:
    container_name: easydemo
    image: easydemo
    build: "./examples"
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./examples:/app