version: '3'
services:
  core:
    container_name: easycore
    image: easycore
    build: .
    restart: always
    ports:
      - "5000:7000"
    volumes:
      - .:/app

  demo:
    container_name: easydemo
    image: easydemo
    build: "./examples"
    restart: always
    ports:
      - "8080:7000"
    volumes:
      - ./examples:/app

  admin:
    container_name: easyadmin
    image: easyadmin
    build: "../sociallogin-web"
    restart: always
    ports:
      - "8000:7000"
    volumes:
      - ../sociallogin:/app