version: '3'
services:
  core:
    container_name: easycore
    image: easycore
    build: .
    restart: always
    ports:
      - "8001:7000"
    volumes:
      - .:/app

  demo:
    container_name: easydemo
    image: easydemo
    build: "./examples"
    restart: always
    ports:
      - "8002:7000"
    volumes:
      - ./examples:/app
